FROM python:3.8-slim

COPY ./backend .

COPY Koordinaten.json .

RUN pip install -r requirements.txt

EXPOSE 8000

ENV FLASK_APP=influxdb_to_json.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]