name: my_web_project
description: A new Flutter web project with Flutter Map integration.

# Version of your application
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Neueste Version von flutter_map und die benötigten Pakete
  flutter_map: ^7.0.2
  
  # Aktualisierte Version von latlong2 für flutter_map ^7.0.2
  latlong2: ^0.9.1

  # Kompatible Version von http für flutter_map
  http: ^1.2.1

  # Für die Formatierung von Zeitstempeln
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Registriere die JSON-Datei als Asset

